### PR TITLE
Remove www. from gratipay.com in README

### PR DESCRIPTION
**Pull request by chadwhitacre**
@twolfson We're not using `www.` anymore since the rename.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Also, our general pattern is to make PRs from a branch in the shared repo (rather than from personal forks). Are you comfortable with that?

We also have a policy that edits to documentation such as the README can be made directly on master. I haven't done that here because I didn't want to step on your toes. Are you okay with "doc on master"? :-)

**Comment by twolfson** [comment]
Removing `www.` can lead to additional overhead and maintenance headaches in the future. Was there a thread I can chime into to move it back to `www.`?

http://www.yes-www.org/why-use-www/

Yea, I am okay with branches on the repo. I usually have a prefix of `dev/` or `bug/` for branch intent.

I would still prefer PRs for documentation updates.

**Comment by chadwhitacre** [comment]
We don't have an issue to move back to `www.`, no. The resource you mention was mentioned at https://github.com/gratipay/inside.gratipay.com/issues/73#issuecomment-53454582, with my response in the next comment.

> Yea, I am okay with branches on the repo. I usually have a prefix of dev/ or bug/ for branch intent.
> 
> I would still prefer PRs for documentation updates.

Okay. Could we mention this in a `CONTRIBUTING.md`?

**Comment by twolfson** [comment]
Alright, I am taking care of `CONTRIBUTING.md` in a separate update. This PR has been merged/released in `2.1.0`.

**Comment by twolfson** [comment]
I took a bit of a detour but eventually added the `CONTRIBUTING.md` in `2.1.2`. :+1:

**Pull request merged**
